### ISSUE TITLE
测试了最新的雷电9模拟器X64位的。逍遥模拟器X86位的都无法使用，报错如下

### ISSUE THREAD

**Issue by sd3970566** [Eurya2233369/LuaJit-Android#1]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.eurya.luajit-1/base.apk"],nativeLibraryDirectories=[/data/app/com.eurya.luajit-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libluajava.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:985)
        at java.lang.System.loadLibrary(System.java:1562)
        at org.keplerproject.luajava.LuaState.<clinit>(LuaState.java:94)
        at org.keplerproject.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
        at com.eurya.luajit.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:6760)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

百度上让我加个这个，但是我加了也没效果···和没加的报错都一样
 defaultConfig {
        applicationId "com.eurya.luajit"
        minSdkVersion 19
        targetSdkVersion 23
        ndk { abiFilters "armeabi-v7a","x86","x86_64"}//加了这个。但是还是一样的报错。
        versionCode 1
        versionName "1.0"
    }

**Comment by Eurya2233369** [comment]
好的我会对这个问题进行处理的

**Comment by Eurya2233369** [comment]
我好像忘了上传.c的文件
